import os
from typing import Any, Generator

import pytest


@pytest.fixture()
def _setup_get_config() -> Generator[None, None, None]:
    url = "http://localhost:9200"

    if os.getenv("STAGE") == "development":
        url = "http://elasticsearch:9200"

    os.environ["ES_INDEX"] = "pokemon"
    os.environ["ES_CONNECTION_URL"] = url
    yield
    del os.environ["ES_INDEX"]
    del os.environ["ES_CONNECTION_URL"]


@pytest.fixture()
def setup_conditions_mimikkyu_res() -> list[dict[str, Any]]:
    return [
        {
            "abilities": {
                "ability_1": "ばけのかわ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 90,
                "base_total": 476,
                "defense": 80,
                "hp": 55,
                "special_attack": 50,
                "special_defense": 105,
                "speed": 96,
            },
            "form": "ばれたすがた",
            "gender_type": {"has_female": True, "has_male": True},
            "height": 0.2,
            "is_legendary": False,
            "is_mega_evolution": False,
            "is_mythical": False,
            "is_primal_reversion": False,
            "name": "ミミッキュ",
            "national_pokedex_number": 778,
            "pokemon_type": {"type_1": "ゴースト", "type_2": "フェアリー"},
            "regional_variant": None,
            "weight": 0.7,
        },
        {
            "abilities": {
                "ability_1": "ばけのかわ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 90,
                "base_total": 476,
                "defense": 80,
                "hp": 55,
                "special_attack": 50,
                "special_defense": 105,
                "speed": 96,
            },
            "form": "ばけたすがた",
            "gender_type": {"has_female": True, "has_male": True},
            "height": 0.2,
            "is_legendary": False,
            "is_mega_evolution": False,
            "is_mythical": False,
            "is_primal_reversion": False,
            "name": "ミミッキュ",
            "national_pokedex_number": 778,
            "pokemon_type": {"type_1": "ゴースト", "type_2": "フェアリー"},
            "regional_variant": None,
            "weight": 0.7,
        },
    ]


@pytest.fixture()
def setup_conditions_bool_res() -> list[dict[str, Any]]:
    return [
        {
            "abilities": {
                "ability_1": "おわりのだいち",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 180,
                "base_total": 770,
                "defense": 160,
                "hp": 100,
                "special_attack": 150,
                "special_defense": 90,
                "speed": 90,
            },
            "form": None,
            "gender_type": {"has_female": False, "has_male": False},
            "height": 5.0,
            "is_legendary": True,
            "is_mega_evolution": False,
            "is_mythical": False,
            "is_primal_reversion": True,
            "name": "ゲンシグラードン",
            "national_pokedex_number": 383,
            "pokemon_type": {"type_1": "じめん", "type_2": "ほのお"},
            "regional_variant": None,
            "weight": 999.7,
        },
        {
            "abilities": {
                "ability_1": "ひでり",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 150,
                "base_total": 670,
                "defense": 140,
                "hp": 100,
                "special_attack": 100,
                "special_defense": 90,
                "speed": 90,
            },
            "form": None,
            "gender_type": {"has_female": False, "has_male": False},
            "height": 3.5,
            "is_legendary": True,
            "is_mega_evolution": False,
            "is_mythical": False,
            "is_primal_reversion": False,
            "name": "グラードン",
            "national_pokedex_number": 383,
            "pokemon_type": {"type_1": "じめん", "type_2": None},
            "regional_variant": None,
            "weight": 950.0,
        },
        {
            "abilities": {
                "ability_1": "はじまりのうみ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 150,
                "base_total": 770,
                "defense": 90,
                "hp": 100,
                "special_attack": 180,
                "special_defense": 160,
                "speed": 90,
            },
            "form": None,
            "gender_type": {"has_female": False, "has_male": False},
            "height": 9.8,
            "is_legendary": True,
            "is_mega_evolution": False,
            "is_mythical": False,
            "is_primal_reversion": True,
            "name": "ゲンシカイオーガ",
            "national_pokedex_number": 382,
            "pokemon_type": {"type_1": "みず", "type_2": None},
            "regional_variant": None,
            "weight": 430.0,
        },
        {
            "abilities": {
                "ability_1": "あめふらし",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 100,
                "base_total": 670,
                "defense": 90,
                "hp": 100,
                "special_attack": 150,
                "special_defense": 140,
                "speed": 90,
            },
            "form": None,
            "gender_type": {"has_female": False, "has_male": False},
            "height": 4.5,
            "is_legendary": True,
            "is_mega_evolution": False,
            "is_mythical": False,
            "is_primal_reversion": False,
            "name": "カイオーガ",
            "national_pokedex_number": 382,
            "pokemon_type": {"type_1": "みず", "type_2": None},
            "regional_variant": None,
            "weight": 352.0,
        },
        {
            "abilities": {
                "ability_1": "シンクロ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 100,
                "base_total": 600,
                "defense": 100,
                "hp": 100,
                "special_attack": 100,
                "special_defense": 100,
                "speed": 100,
            },
            "form": None,
            "gender_type": {"has_female": False, "has_male": False},
            "height": 0.4,
            "is_legendary": True,
            "is_mega_evolution": False,
            "is_mythical": True,
            "is_primal_reversion": False,
            "name": "ミュウ",
            "national_pokedex_number": 151,
            "pokemon_type": {"type_1": "エスパー", "type_2": None},
            "regional_variant": None,
            "weight": 4.0,
        },
        {
            "abilities": {
                "ability_1": "ふみん",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 150,
                "base_total": 780,
                "defense": 70,
                "hp": 106,
                "special_attack": 194,
                "special_defense": 120,
                "speed": 140,
            },
            "form": None,
            "gender_type": {"has_female": False, "has_male": False},
            "height": 1.5,
            "is_legendary": True,
            "is_mega_evolution": True,
            "is_mythical": False,
            "is_primal_reversion": False,
            "name": "メガミュウツーＹ",
            "national_pokedex_number": 150,
            "pokemon_type": {"type_1": "エスパー", "type_2": None},
            "regional_variant": None,
            "weight": 33.0,
        },
        {
            "abilities": {
                "ability_1": "ふくつのこころ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "attack": 190,
                "base_total": 780,
                "defense": 100,
                "hp": 106,
                "special_attack": 154,
                "special_defense": 100,
                "speed": 130,
            },
            "form": None,
            "gender_type": {"has_female": False, "has_male": False},
            "height": 2.3,
            "is_legendary": True,
            "is_mega_evolution": True,
            "is_mythical": False,
            "is_primal_reversion": False,
            "name": "メガミュウツーＸ",
            "national_pokedex_number": 150,
            "pokemon_type": {"type_1": "エスパー", "type_2": "かくとう"},
            "regional_variant": None,
            "weight": 127.0,
        },
        {
            "abilities": {
                "ability_1": "プレッシャー",
                "ability_2": None,
                "hidden_ability": "きんちょうかん",
            },
            "base_stats": {
                "attack": 110,
                "base_total": 680,
                "defense": 90,
                "hp": 106,
                "special_attack": 154,
                "special_defense": 90,
                "speed": 130,
            },
            "form": None,
            "gender_type": {"has_female": False, "has_male": False},
            "height": 2.0,
            "is_legendary": True,
            "is_mega_evolution": False,
            "is_mythical": False,
            "is_primal_reversion": False,
            "name": "ミュウツー",
            "national_pokedex_number": 150,
            "pokemon_type": {"type_1": "エスパー", "type_2": None},
            "regional_variant": None,
            "weight": 122.0,
        },
    ]


@pytest.fixture()
def setup_null_conditions_res() -> list[dict[str, Any]]:
    return [
        {
            "national_pokedex_number": 778,
            "name": "ミミッキュ",
            "form": "ばれたすがた",
            "regional_variant": None,
            "is_mega_evolution": False,
            "is_primal_reversion": False,
            "is_legendary": False,
            "is_mythical": False,
            "height": 0.2,
            "weight": 0.7,
            "gender_type": {"has_male": True, "has_female": True},
            "pokemon_type": {"type_1": "ゴースト", "type_2": "フェアリー"},
            "abilities": {
                "ability_1": "ばけのかわ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 55,
                "attack": 90,
                "defense": 80,
                "special_attack": 50,
                "special_defense": 105,
                "speed": 96,
                "base_total": 476,
            },
        },
        {
            "national_pokedex_number": 778,
            "name": "ミミッキュ",
            "form": "ばけたすがた",
            "regional_variant": None,
            "is_mega_evolution": False,
            "is_primal_reversion": False,
            "is_legendary": False,
            "is_mythical": False,
            "height": 0.2,
            "weight": 0.7,
            "gender_type": {"has_male": True, "has_female": True},
            "pokemon_type": {"type_1": "ゴースト", "type_2": "フェアリー"},
            "abilities": {
                "ability_1": "ばけのかわ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 55,
                "attack": 90,
                "defense": 80,
                "special_attack": 50,
                "special_defense": 105,
                "speed": 96,
                "base_total": 476,
            },
        },
        {
            "national_pokedex_number": 383,
            "name": "ゲンシグラードン",
            "form": None,
            "regional_variant": None,
            "is_mega_evolution": False,
            "is_primal_reversion": True,
            "is_legendary": True,
            "is_mythical": False,
            "height": 5,
            "weight": 999.7,
            "gender_type": {"has_male": False, "has_female": False},
            "pokemon_type": {"type_1": "じめん", "type_2": "ほのお"},
            "abilities": {
                "ability_1": "おわりのだいち",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 100,
                "attack": 180,
                "defense": 160,
                "special_attack": 150,
                "special_defense": 90,
                "speed": 90,
                "base_total": 770,
            },
        },
        {
            "national_pokedex_number": 383,
            "name": "グラードン",
            "form": None,
            "regional_variant": None,
            "is_mega_evolution": False,
            "is_primal_reversion": False,
            "is_legendary": True,
            "is_mythical": False,
            "height": 3.5,
            "weight": 950,
            "gender_type": {"has_male": False, "has_female": False},
            "pokemon_type": {"type_1": "じめん", "type_2": None},
            "abilities": {
                "ability_1": "ひでり",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 100,
                "attack": 150,
                "defense": 140,
                "special_attack": 100,
                "special_defense": 90,
                "speed": 90,
                "base_total": 670,
            },
        },
        {
            "national_pokedex_number": 382,
            "name": "ゲンシカイオーガ",
            "form": None,
            "regional_variant": None,
            "is_mega_evolution": False,
            "is_primal_reversion": True,
            "is_legendary": True,
            "is_mythical": False,
            "height": 9.8,
            "weight": 430,
            "gender_type": {"has_male": False, "has_female": False},
            "pokemon_type": {"type_1": "みず", "type_2": None},
            "abilities": {
                "ability_1": "はじまりのうみ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 100,
                "attack": 150,
                "defense": 90,
                "special_attack": 180,
                "special_defense": 160,
                "speed": 90,
                "base_total": 770,
            },
        },
        {
            "national_pokedex_number": 382,
            "name": "カイオーガ",
            "form": None,
            "regional_variant": None,
            "is_mega_evolution": False,
            "is_primal_reversion": False,
            "is_legendary": True,
            "is_mythical": False,
            "height": 4.5,
            "weight": 352,
            "gender_type": {"has_male": False, "has_female": False},
            "pokemon_type": {"type_1": "みず", "type_2": None},
            "abilities": {
                "ability_1": "あめふらし",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 100,
                "attack": 100,
                "defense": 90,
                "special_attack": 150,
                "special_defense": 140,
                "speed": 90,
                "base_total": 670,
            },
        },
        {
            "national_pokedex_number": 151,
            "name": "ミュウ",
            "form": None,
            "regional_variant": None,
            "is_mega_evolution": False,
            "is_primal_reversion": False,
            "is_legendary": True,
            "is_mythical": True,
            "height": 0.4,
            "weight": 4,
            "gender_type": {"has_male": False, "has_female": False},
            "pokemon_type": {"type_1": "エスパー", "type_2": None},
            "abilities": {
                "ability_1": "シンクロ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 100,
                "attack": 100,
                "defense": 100,
                "special_attack": 100,
                "special_defense": 100,
                "speed": 100,
                "base_total": 600,
            },
        },
        {
            "national_pokedex_number": 150,
            "name": "メガミュウツーＹ",
            "form": None,
            "regional_variant": None,
            "is_mega_evolution": True,
            "is_primal_reversion": False,
            "is_legendary": True,
            "is_mythical": False,
            "height": 1.5,
            "weight": 33,
            "gender_type": {"has_male": False, "has_female": False},
            "pokemon_type": {"type_1": "エスパー", "type_2": None},
            "abilities": {
                "ability_1": "ふみん",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 106,
                "attack": 150,
                "defense": 70,
                "special_attack": 194,
                "special_defense": 120,
                "speed": 140,
                "base_total": 780,
            },
        },
        {
            "national_pokedex_number": 150,
            "name": "メガミュウツーＸ",
            "form": None,
            "regional_variant": None,
            "is_mega_evolution": True,
            "is_primal_reversion": False,
            "is_legendary": True,
            "is_mythical": False,
            "height": 2.3,
            "weight": 127,
            "gender_type": {"has_male": False, "has_female": False},
            "pokemon_type": {"type_1": "エスパー", "type_2": "かくとう"},
            "abilities": {
                "ability_1": "ふくつのこころ",
                "ability_2": None,
                "hidden_ability": None,
            },
            "base_stats": {
                "hp": 106,
                "attack": 190,
                "defense": 100,
                "special_attack": 154,
                "special_defense": 100,
                "speed": 130,
                "base_total": 780,
            },
        },
        {
            "national_pokedex_number": 150,
            "name": "ミュウツー",
            "form": None,
            "regional_variant": None,
            "is_mega_evolution": False,
            "is_primal_reversion": False,
            "is_legendary": True,
            "is_mythical": False,
            "height": 2,
            "weight": 122,
            "gender_type": {"has_male": False, "has_female": False},
            "pokemon_type": {"type_1": "エスパー", "type_2": None},
            "abilities": {
                "ability_1": "プレッシャー",
                "ability_2": None,
                "hidden_ability": "きんちょうかん",
            },
            "base_stats": {
                "hp": 106,
                "attack": 110,
                "defense": 90,
                "special_attack": 154,
                "special_defense": 90,
                "speed": 130,
                "base_total": 680,
            },
        },
    ]
