version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/python/Dockerfile
    env_file:
      - ../.env.$STAGE
    volumes:
      - ..:/workspace
    networks:
      - private
    ports:
      - 8000:8000
    command: /bin/bash -c "uvicorn pokeapi.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - elasticsearch
  elasticsearch:
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - discovery.type=single-node
    networks:
      - private
    ports:
      - 9200:9200
  elasticdump:
    build:
      context: .
      dockerfile: ./elasticdump/Dockerfile
    platform: linux/amd64
    networks:
      - private
    depends_on:
      - elasticsearch
    entrypoint: bash /tmp/entrypoint.sh
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    platform: linux/amd64
    networks:
      - private
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  private:
