name: Static code analysis with flake8

run-name: ${{ github.actor }} is running static analysis with flake8

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  flake8:
    runs-on: ubuntu-22.04
    strategy:
        matrix:
          python-version: ["3.10"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Branch Check
        run: |
          echo Branch: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run flake8
        uses: reviewdog/action-flake8@v3
        with:
          reporter: github-pr-review
          level: warning
