name: Continuous Integration of pokeapi

run-name: ${{ github.actor }} is testing out pokeapi

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build containers
        run: |
          STAGE=development docker-compose -f docker/docker-compose.yml up -d --build
      - name: Wait for pokeapi to start
        run: sleep 20s
      - name: Get container ID
        run: |
          echo "CONTAINER_ID=$(STAGE=development docker-compose -f docker/docker-compose.yml ps -q app)" >> $GITHUB_ENV
      - name: Get container IP address
        run: |
          echo "IP_ADDRESS=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ env.CONTAINER_ID }})" >> $GITHUB_ENV
      - name: Test pokeapi with curl
        run: |
          curl http://${{ env.IP_ADDRESS }}:8000/ >> $GITHUB_STEP_SUMMARY
